CREATE TABLE IF NOT EXISTS `compras` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `proveedor_id` bigint(20) UNSIGNED NOT NULL,
  `numero_comprobante` varchar(50) NOT NULL,
  `tipo_comprobante` varchar(20) NOT NULL,
  `fecha_compra` date NOT NULL,
  `subtotal` decimal(12,2) NOT NULL,
  `igv` decimal(12,2) NOT NULL,
  `total` decimal(12,2) NOT NULL,
  `descripcion` text DEFAULT NULL,
  `clasificacion` varchar(50) DEFAULT NULL,
  `estado` varchar(20) DEFAULT 'registrado',
  `pdf_url` varchar(255) DEFAULT NULL,
  `xml_url` varchar(255) DEFAULT NULL,
  `proyecto_id` BIGINT UNSIGNED NULL COMMENT 'Proyecto asociado',
  `contrato_id` BIGINT UNSIGNED NULL COMMENT 'Contrato asociado',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fecha_compra` (`fecha_compra`),
  KEY `proveedor_id` (`proveedor_id`),
  KEY `idx_proyecto` (`proyecto_id`),
  KEY `idx_contrato` (`contrato_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
